version: '3'

services:
  redis:
    image: redis
  app1:
    build:
      context: ./app
    hostname: app1
    links:
      - redis
  app2:
    build:
      context: ./app
    hostname: app2
    links:
      - redis
  app3:
    build:
      context: ./app
    hostname: app3
    links:
      - redis
  lb:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    links:
      - app1
      - app2
      - app3
    restart: always
