version: '3.2'

services:
  redis:
    image: redis
    networks:
      - backend
  app1:
    build:
      context: ./app
    hostname: app1
    networks:
      - frontend
      - backend
    links:
      - redis
  app2:
    build:
      context: ./app
    hostname: app2
    networks:
      - frontend
      - backend
    links:
      - redis
  app3:
    build:
      context: ./app
    hostname: app3
    networks:
      - frontend
      - backend
    links:
      - redis
  lb:
    image: nginx:${NGINX_VERSION}
    ports:
      - "8000:80"
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    hostname: proxy
    networks:
      - frontend
    links:
      - app1
      - app2
      - app3
    restart: always
networks:
  frontend:
  backend:
